In [1]:
import pandas as pd
import numpy as np
import streamlit as st
data1 = pd.read_csv('Data/github_dataset.csv')

In [2]:
data1.shape

(1052, 7)

In [3]:
data1.isna().sum(axis = 0)

repositories       0
stars_count        0
forks_count        0
issues_count       0
pull_requests      0
contributors       0
language         145
dtype: int64

In [4]:
data1[data1['language'].isna()]

,repositories,stars_count,forks_count,issues_count,pull_requests,contributors,language
0,octocat/Hello-World,0,0,612,316,2,NaN
1,EddieHubCommunity/support,271,150,536,6,71,NaN
10,taniarascia/comments,4,0,117,0,0,NaN
30,florinpop17/app-ideas,0,0,46,235,68,NaN
37,education/teachers,176,28,39,0,2,NaN
...,...,...,...,...,...,...,...
1014,offensive-security/Kali-WSL-chroot,40,17,1,1,2,NaN
1015,joelparkerhenderson/architecture-decision-record,0,0,1,0,26,NaN
1019,sefakozan/turkce-iptv,48,10,1,1,0,NaN
1032,mikenikles/gitpod-minimal-custom-dockerfile,3,1,1,1,0,NaN
1042,varunKT001/git-github-hIQ-fork,1,1,1,0,2,NaN

In [5]:
data1.fillna('Not Specified', inplace = True)

In [6]:
data1.describe(include = 'all')

,repositories,stars_count,forks_count,issues_count,pull_requests,contributors,language
count,1052,1052.000000,1052.000000,1052.000000,1052.000000,1052.000000,1052
unique,972,NaN,NaN,NaN,NaN,NaN,52
top,kameshsampath/ansible-role-rosa-demos,NaN,NaN,NaN,NaN,NaN,JavaScript
freq,2,NaN,NaN,NaN,NaN,NaN,253
mean,NaN,81.976236,53.884981,8.656844,4.374525,8.364068,NaN
std,NaN,170.403116,127.699729,32.445154,27.913732,37.511807,NaN
min,NaN,0.000000,0.000000,1.000000,0.000000,0.000000,NaN
25%,NaN,1.000000,1.000000,1.000000,0.000000,0.000000,NaN
50%,NaN,12.000000,6.000000,2.000000,0.000000,2.000000,NaN
75%,NaN,65.250000,38.250000,6.000000,2.000000,4.000000,NaN
max,NaN,995.000000,973.000000,612.000000,567.000000,658.000000,NaN

In [7]:
data2 = pd.read_csv('Data/repository_data.csv')

In [8]:
data2.shape

(2917951, 10)

In [9]:
data2['languages_used'][0]

"['TypeScript', 'JavaScript', 'CSS', 'Shell', 'Dockerfile', 'EJS', 'HTML', 'Less']"

In [10]:
data2.isna().sum()

name                     12
stars_count               0
forks_count               0
watchers                  0
pull_requests             0
primary_language     218573
languages_used       221984
commit_count           1921
created_at                0
licence             1378200
dtype: int64

In [11]:
data1.columns

Index(['repositories', 'stars_count', 'forks_count', 'issues_count',
       'pull_requests', 'contributors', 'language'],
      dtype='object')

In [12]:
type(data1['repositories'][0])

str

In [13]:
   def get_data():
    return pd.read_csv('Data/github_dataset.csv')

df = get_data()
df.fillna('Not Specified', inplace=True)
df1 = df.sort_values(by = 'stars_count', ascending = False)[:10].reset_index().drop('index', axis = 1)

In [14]:
data1['language'].unique()

array(['Not Specified', 'C++', 'Python', 'Ruby', 'Java', 'CSS', 'Jinja',
       'Dart', 'JavaScript', 'HTML', 'Objective-C', 'Kotlin',
       'AutoHotkey', 'Go', 'Haskell', 'SCSS', 'Jupyter Notebook', 'Vue',
       'Shell', 'Rust', 'PowerShell', 'C', 'C#', 'TypeScript', 'Svelte',
       'Less', 'QML', 'CoffeeScript', 'Swift', 'Hack', 'PHP', 'Smarty',
       'Solidity', 'Dockerfile', 'PureBasic', 'Vim Script', 'R', 'HCL',
       'Perl', 'Makefile', 'Roff', 'ActionScript', 'CodeQL', 'Elixir',
       'Oz', 'CMake', 'Assembly', 'Pawn', 'Gherkin', 'QMake', 'Cuda',
       'SourcePawn'], dtype=object)

In [15]:
data2['created_at'].unique()

array(['2014-12-24T17:49:19Z', '2019-03-26T07:31:14Z',
       '2013-10-11T06:50:37Z', ..., '2022-01-26T19:08:25Z',
       '2022-01-24T03:27:16Z', '2022-01-22T00:00:12Z'], dtype=object)

In [16]:
from datetime import datetime
datetime.strptime(data2['created_at'][0], '%Y-%m-%dT%H:%M:%SZ').date()

datetime.date(2014, 12, 24)

In [17]:
data2.columns

Index(['name', 'stars_count', 'forks_count', 'watchers', 'pull_requests',
       'primary_language', 'languages_used', 'commit_count', 'created_at',
       'licence'],
      dtype='object')

In [18]:
data2['languages_used'] = data2['languages_used'].fillna('Not Specified')

In [19]:
data2['languages_used'][0].split("', '")[1:len(data2['languages_used'][0].split(',')) - 1]

['JavaScript', 'CSS', 'Shell', 'Dockerfile', 'EJS', 'HTML']

In [20]:
data2.head()

,name,stars_count,forks_count,watchers,pull_requests,primary_language,languages_used,commit_count,created_at,licence
0,freeCodeCamp,359805,30814,8448,31867,TypeScript,"['TypeScript', 'JavaScript', 'CSS', 'Shell', '...",32231.0,2014-12-24T17:49:19Z,"BSD 3-Clause ""New"" or ""Revised"" License"
1,996.ICU,264811,21470,4298,1949,NaN,Not Specified,3189.0,2019-03-26T07:31:14Z,Other
2,free-programming-books,262380,53302,9544,8235,NaN,Not Specified,8286.0,2013-10-11T06:50:37Z,Other
3,coding-interview-university,244927,65038,8539,867,NaN,Not Specified,2314.0,2016-06-06T02:34:12Z,Creative Commons Attribution Share Alike 4.0 I...
4,awesome,235223,24791,7446,1859,NaN,Not Specified,1074.0,2014-07-11T13:42:37Z,Creative Commons Zero v1.0 Universal

In [21]:
from collections import Counter
l = []
for i in data2['languages_used']:
    list1 = i.split("', '")[1:len(i.split(',')) - 1] if i != 'Not Specified' else [i]
    l.extend([item for item in list1])
dic1 = Counter(l)

In [22]:
data2['primary_language'].fillna('Not Specified', inplace = True)

In [23]:
dic2 = Counter(data2['primary_language'])

In [24]:
table1 = pd.DataFrame.from_dict(dic1, orient = 'index').reset_index()
table2 = pd.DataFrame.from_dict(dic2, orient = 'index').reset_index()
table1['Label'] = 'Languages Used'
table2['Label'] = 'Primary Language'
table3 = pd.concat([table1, table2])
table3.columns = ['Language', 'Count', 'Label']
table3[table3['Count'] > 5000].shape

(86, 3)

In [25]:
table3['Language'].values

array(['JavaScript', 'CSS', 'Shell', ..., 'Quake', 'CSV', 'TOML'],
      dtype=object)

In [26]:
data1['language'].unique().shape

(52,)

In [28]:
data1.columns[~data1.columns.isin(data2.columns)]

Index(['repositories', 'issues_count', 'contributors', 'language'], dtype='object')

In [29]:
data1.columns

Index(['repositories', 'stars_count', 'forks_count', 'issues_count',
       'pull_requests', 'contributors', 'language'],
      dtype='object')

In [30]:
df.columns

Index(['repositories', 'stars_count', 'forks_count', 'issues_count',
       'pull_requests', 'contributors', 'language'],
      dtype='object')

In [31]:
df = data1.copy(deep = True)
df4 = df.groupby('repositories').count().reset_index().sort_values(by = 'contributors', ascending = False)[['repositories', 'contributors']]
df4.rename(columns = {'contributors':'contributor_count'}, inplace = True)
df5 = df.groupby('repositories').sum().reset_index().sort_values(by = 'stars_count', ascending = False)[['repositories', 'stars_count', 'forks_count']]
df6 = pd.merge(df4, df5, on = 'repositories')
df7 = df6.copy(deep = True)[['repositories', 'contributor_count', 'stars_count']]
df7.rename(columns = {'stars_count':'count'}, inplace = True)
df7['label'] = 'Stars'
df8 = df6.copy(deep = True)[['repositories', 'contributor_count', 'forks_count']]
df8.rename(columns = {'forks_count':'count'}, inplace = True)
df8['label'] = 'Forks'
df9 = pd.concat([df7, df8])

In [32]:
df3 = data1.groupby('language').count()

In [33]:
df3

,repositories,stars_count,forks_count,issues_count,pull_requests,contributors
language,,,,,,
ActionScript,1,1,1,1,1,1
Assembly,2,2,2,2,2,2
AutoHotkey,3,3,3,3,3,3
C,26,26,26,26,26,26
C#,8,8,8,8,8,8
C++,29,29,29,29,29,29
CMake,1,1,1,1,1,1
CSS,37,37,37,37,37,37
CodeQL,2,2,2,2,2,2
CoffeeScript,3,3,3,3,3,3
Cuda,1,1,1,1,1,1
Dart,36,36,36,36,36,36
Dockerfile,3,3,3,3,3,3
Elixir,2,2,2,2,2,2
Gherkin,1,1,1,1,1,1
Go,15,15,15,15,15,15
HCL,1,1,1,1,1,1
HTML,72,72,72,72,72,72
Hack,2,2,2,2,2,2
Haskell,1,1,1,1,1,1
Java,44,44,44,44,44,44
JavaScript,253,253,253,253,253,253
Jinja,5,5,5,5,5,5
Jupyter Notebook,29,29,29,29,29,29
Kotlin,7,7,7,7,7,7
Less,1,1,1,1,1,1
Makefile,6,6,6,6,6,6
Not Specified,145,145,145,145,145,145
Objective-C,8,8,8,8,8,8
Oz,1,1,1,1,1,1
PHP,16,16,16,16,16,16
Pawn,2,2,2,2,2,2
Perl,3,3,3,3,3,3
PowerShell,2,2,2,2,2,2
PureBasic,1,1,1,1,1,1
Python,155,155,155,155,155,155
QML,1,1,1,1,1,1
QMake,1,1,1,1,1,1
R,1,1,1,1,1,1
Roff,1,1,1,1,1,1
Ruby,28,28,28,28,28,28
Rust,10,10,10,10,10,10
SCSS,4,4,4,4,4,4
Shell,25,25,25,25,25,25
Smarty,1,1,1,1,1,1
Solidity,3,3,3,3,3,3
SourcePawn,1,1,1,1,1,1
Svelte,1,1,1,1,1,1
Swift,10,10,10,10,10,10
TypeScript,37,37,37,37,37,37
Vim Script,2,2,2,2,2,2
Vue,2,2,2,2,2,2

In [34]:
df.groupby('repositories').count()['stars_count'].value_counts()

1    892
2     80
Name: stars_count, dtype: int64

In [35]:
df10 = df[['repositories', 'contributors']].copy(deep = True)

In [36]:
df10.values

array([['octocat/Hello-World', 2],
       ['EddieHubCommunity/support', 71],
       ['ethereum/aleth', 154],
       ...,
       ['aitikgupta/interactive_cpu_scheduler', 7],
       ['gwmccubbin/voting_dapp', 0],
       ['gamemann/All_PropHealth', 0]], dtype=object)